### ISSUE TITLE
Am I able to fetch an on-call list for users or escalation policies

### ISSUE THREAD

**Issue by zentavr** [dropbox/pygerduty#16]
PagerDuty API docs says that we are able to fetch on call lists:
https://developer.pagerduty.com/documentation/rest/escalation_policies/on_call
https://developer.pagerduty.com/documentation/rest/users/on_call

I wonder if there is an example or ability to do thta using this library?

**Comment by gmjosack** [comment]
That appears to be a newer endpoint that isn't supported at the moment. We'll take a look at adding support for that soon.

Thanks!

**Comment by gmjosack** [comment]
Sorry for the delay. This is now supported on Users and EscalationPolicies.

For example:

```python
pd.escalation_policies.on_call()
pd.users.on_call()
```

parameters can be passed in the same way as the `list` method

This has been updated in the latest version on PyPI. Thanks for the report!
