### ISSUE TITLE
Passing array values for parameters (example: ?include[]=escalation_policy) in requests

### ISSUE THREAD

**Issue by kmerrill** [dropbox/pygerduty#17]
Can we add support for array parameters in requests?

```python
pd = pygerduty.PagerDuty(NAME, API_KEY)
pd.services.show(service_id, include='escalation_policy')
```

I need a request to pass a url that looks like:
https://subdomain.pagerduty.com/api/v1/services/XXXXXXX?include[]=escalation_policy

Keyword arguments do not support brackets so the request becomes malformed:
https://subdomain.pagerduty.com/api/v1/services/XXXXXXX?include=escalation_policy
```
pygerduty.BadRequest: Invalid Parameters (99999): {u'include': [u'Include must be an Array']}
```

```python
    def request(self, method, path, query_params=None, data=None,
                extra_headers=None):
# lines omitted
        if query_params is not None:
            query_params = urllib.urlencode(query_params)
```

From the PagerDuty API docs, it looks like there are 3 array parameters: escalation_policies, include, and schedule_layers.

Perhaps, we could add brackets with a regexp?
```python
        if query_params is not None:
            # Add brackets for array keys
            query_params = re.sub(r'(escalation_policies|include|schedule_layers)', 
                                  r'\1[]', urllib.urlencode(query_params))
```

**Comment by gmjosack** [comment]
Thanks for the report! I've just pushed a new version to PyPI. Let me know if you have any issues.

You should be able to just pass lists now and they'll be converted to the syntax the api expects for array types.

For example:

```python
pd.services.list(include=["escalation_policy", "email_filters"])
```

**Comment by kmerrill** [comment]
A very elegant solution, indeed. Thanks!

On Tue, Mar 3, 2015 at 8:00 PM, Gary M. Josack <notifications@github.com>
wrote:

> Thanks for the report! I've just pushed a new version to PyPI. Let me know
> if you have any issues.
>
> You should be able to just pass lists now and they'll be converted to the
> syntax the api expects for array types.
>
> For example:
>
> pd.services.list(include=["escalation_policy", "email_filters"])
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dropbox/pygerduty/issues/17#issuecomment-77093418>.
>



-- 
Kris Merrill - Site Reliability Engineer - Twitter, Inc.
