### ISSUE TITLE
Python3 issues

### ISSUE THREAD

**Issue by chris-martin** [dropbox/pygerduty#22]
Not-necessarily-exhaustive list of Python 3 issues:

* `urllib2` module is gone - is replaced by `urllib.request` and `urllib.error`
* `urlparse` module is renamed to `urllib.parse`
* `dict.iteritems` is gone, replaced by `items`. This exists in python 2, but with nonlazy semantics, not a breaking change to switch.
* `%` syntax for formatting strings is gone. Replace `'... %s ...' % x` with `'... {} ...'.format(x)` - Unfortunately this was added in 2.6, so this is a breaking change for 2.5
* Relative imports must be explicit. `from version import ...` changes to `from .version import ...`

**Comment by chris-martin** [comment]
I've made these changes in my fork:

* https://pypi.python.org/pypi/pygerduty-py3
* https://github.com/cardforcoin/pygerduty/tree/py3

I'd be happy to transfer ownership of the pypi name if anyone else cares to take over its maintenance.

**Comment by saj** [comment]
From the `README`:

> Pygerduty is tested against >= Python 2.5

That minor release is notably missing from [travis.yml](https://github.com/dropbox/pygerduty/blob/d480bf41710138b70dc858390a8a446c0efe8528/.travis.yml).  @gmjosack, Is Python 2.5 still supported or is the `README` simply out of date?

Dropping support for py2.5 may be more reasonable than maintaining a fork just for py3.

**Comment by gmjosack** [comment]
I'm not against dropping support for python 2.5 at this point. Python 2.7 is >5 years old at this point and most distros have it by default so I'd be happy to target that. If someone wanted to take on the work of making `pygerduty` both py2.7 and py3.x compatible I would happily merge it.

**Comment by saj** [comment]
Sent PR #28. Includes the contributions from @chris-martin. (Thanks!)
