### ISSUE TITLE
New 'self' fields in PagerDuty REST API responses trigger TypeErrors

### ISSUE THREAD

**Issue by saj** [dropbox/pygerduty#23]
PagerDuty have started returning new `self` fields in their responses.  These fields self-reference the canonical URI of the resource in the response, e.g.:

    {
      [...]
      "self": "https://contoso.pagerduty.com/api/v1/escalation_policies/PABCDEF"
    }

This causes obvious problems in pygerduty when the key-values from the response payload are passed to a `Container` constructor.  The problem typically manifests with a stack trace not unlike:

      File "/Users/saj/.pex/install/pygerduty-0.28-py2-none-any.whl.ba6cbb714c785594762b7f0a3df561c0fae3a825/pygerduty-0.28-py2-none-any.whl/pygerduty/__init__.py", line 84, in create
        return self.container(self, **response.get(self.sname, {}))
    TypeError: __init__() got multiple values for keyword argument 'self'

**Comment by saj** [comment]
I have a support ticket open with PagerDuty about this change to their API.

They are now reporting that the change has been rolled back and may not be seen again.  Please hold off on merging this PR until I hear back from them.  The PR may be unnecessary.  Ta.

**Comment by saj** [comment]
PagerDuty rolled this change back.  I have confirmed that pygerduty 0.28 works as it did before.

**Comment by ryanneufeld** [comment]
This problem has re-surfaced in the latest version. The current v1 api from pager duty still includes a self key, and the fix from #24 no longer appears in the code base.

**Comment by gmjosack** [comment]
Can you confirm whether you're using a v1 or v2 API token? This library only supports v1 which shouldn't be receiving any changes from pagerduty as it is deprecated. If you're using a v2 token it changes the behavior in close, but incompatible ways.

**Comment by ryanneufeld** [comment]
I'm hitting pagerduty.com/api/v1

and well:

'impacted_services": [
        {
          "id": "P1LE44Z",
          "type": "service_reference",
          "summary": "Nagios SRE",
          "self": "https://api.pagerduty.com/services/P1LE44Z",
          "html_url": "https://opendns.pagerduty.com/services/P1LE44Z"
        }
      ],'

**Comment by ryanneufeld** [comment]
My key is type "Events API v1"

**Comment by gmjosack** [comment]
I won't have access to a computer to look for a few hours but can you confirm you're using a v1 token when authing against the API?

**Comment by gmjosack** [comment]
Alright thanks for the report. Will take a look as soon as I can.

**Comment by gmjosack** [comment]
Can you give an explicit reproducible call in pygerduty that I can test with? I've tested a couple rest endpoints as well as the events api and all seem to be working well. Additionally we're not using any issues with our uses of this library currently.

**Comment by ryanneufeld** [comment]
I can't as it would reveal some PII,

But we encountered this as part of a stackstorm-pagerduty pack we were
wanting to use.

--Ryan Neufeld BSc CIS
ryan@neufeldmail.com

**Comment by gmjosack** [comment]
I wouldn't need any tokens or keys, just looking for an endpoint to replicate on. Is this for triggering an incident or calling list/show/update/create/delete/etc on and specific resource?

Keep in mind that the v1 api is going away in 2 months so you likely don't want to start a new project on this library. We haven't looked at updating pygerduty to support v2 as pagerduty themselves has a v2 python client library on their github account and there haven't been any requests to carry this library forward to support v2. We're going to be starting our migrations to the v2 api soon so we'll be deciding soon if pygerduty will support v2 or if we'll be migrating to the new client.

**Comment by ryanneufeld** [comment]
curl -X GET --header 'Authorization: Token token=<token>' '
https://subdomain.pagerduty.com/api/v1/incidents?date_range=all&offset=73200&time_zone=UTC
'

--Ryan Neufeld BSc CIS
ryan@neufeldmail.com

**Comment by gmjosack** [comment]
Using a v2 token I see self in the response but I am unable to replicate when using a v1 token. If you look at https://<subdomain>.pagerduty.com/api_keys you should see either "v1 Legacy" or "v2 Current". This library only works with "v1 Legacy" tokens.

**Comment by ryanneufeld** [comment]
On Thu, May 4, 2017 at 10:27 PM, Gary M. Josack <notifications@github.com>
wrote:

> https://.pagerduty.com/api_keys
>

Thanks, apparently I don't have access to that page... I'll get someone who
does to check.

Thanks for taking the time to help me with this.

--Ryan Neufeld BSc CIS
ryan@neufeldmail.com

**Comment by gmjosack** [comment]
Happy to help. It's very confusing that the v1 url will act like v2 with a v2 token.
