### ISSUE TITLE
Escalation Policies not loading Escalation Rules

### ISSUE THREAD

**Issue by tkensiski** [dropbox/pygerduty#29]
I can fetch the escalation Policy correctly however it does not load the rules properly.
```
u'escalation_rules': <pygerduty.EscalationRulesobjectat0x10b7f21d0>
```

I try to loop on it and get the following:
```
Traceback (most recent call last):
  File "./verify.py", line 30, in <module>
    for rule in escalation_policy.escalation_rules:
TypeError: 'EscalationRules' object is not iterable
```

If I try and print the rules I get back the main escalation policy rather than the rules
```
print escalation_policy.escalation_rules.__dict__
```

Manually fetching the escalation policy via curl returns all the information:
```
TOKEN="YOUR-TOKEN-HERE"
COMPANY="YOUR-COMPANY-NAME-HERE"
curl -H "Content-type: application/json" -H "Authorization: Token token=${TOKEN}" -X GET -G \
    --data-urlencode "include[]=teams" \
    --data-urlencode "query=API Escalation" \
    "https://${COMPANY}.pagerduty.com/api/v1/escalation_policies"
```

So from what I can tell its having issues converting the rules.

Running v0.29.0

**Comment by tkensiski** [comment]
same happens when fetching a policy directly

```
self.pager.escalation_policies.show(escalation_policy_id)
```

**Comment by tkensiski** [comment]
ref: https://github.com/dropbox/pygerduty/pull/30

**Comment by tkensiski** [comment]
So tried a list on escalation_rules it started working!
```
for rule in escalation_policy.escalation_rule.list():
        print rule
...
<EscalationRule: escalation_delay_in_minutes=5, rule_object=<RuleObject: type=u'schedule', id=u'REDACTED', name=u'Primary'>, id=u'REDACTED', targets=[<Container: type=u'schedule', id=u'REDACTED', name=u'Primary'>, <Container: type=u'schedule', id=u'REDACTED', name=u'xTeam Shadow'>]>
<EscalationRule: escalation_delay_in_minutes=5, rule_object=<RuleObject: type=u'schedule', id=u'REDACTED', name=u'Team Backup'>, id=u'REDACTED', targets=[<Container: type=u'schedule', id=u'REDACTED', name=u'Team Backup'>]>
<EscalationRule: escalation_delay_in_minutes=5, rule_object=<RuleObject: type=u'schedule', id=u'REDACTED', name=u'Team Escalation'>, id=u'REDACTED', targets=[<Container: type=u'schedule', id=u'REDACTED', name=u'Team Escalation'>, <Container: name=u'user', color=u'blue', time_zone=None, id=u'REDACTED', type=u'user', email=u'user@email.com'>]>
<EscalationRule: escalation_delay_in_minutes=5, rule_object=<RuleObject: type=u'schedule', id=u'PCHWBP0', name=u'Escalation Manager Rotation'>, id=u'REDACTED', targets=[<Container: type=u'schedule', id=u'REDACTED', name=u'Manager Rotation'>, <Container: type=u'schedule', id=u'REDACTED', name=u'Manager Shadow'>]>
```

**Comment by tkensiski** [comment]
I assumed that it had already loaded these. So now that I know I need to list it and have it "load" them the issue is resolved.

**Comment by gmjosack** [comment]
Yeah, this is a place where the documentation should be improved. Those resources are under their own API endpoints and have to be called for each escalation policy. This is similar to `Notes` on `Incidents`, `Overrides` on `Schedules`, etc. 

Thanks for the report as it illustrates a real documentation problem.

**Comment by tkensiski** [comment]
Yeah what I dont understand, while yes I understand that the API has endpoints for all of this but on the initial fetch of the escalation policy it includes the escalation rules "free of charge". While this doesnt need to be super efficient it is sure making a lot of fetches to the API for data that was already retrieved.

**Comment by gmjosack** [comment]
Ah yeah, this seems to be a namespace collision in the way the API is designed. It tries to be clever but it seems it's broken down here unfortunately. I'd have to think of the best way to solve this but it might require some backward incompatible changes.
