### ISSUE TITLE
Python3 failure in create_event

### ISSUE THREAD

**Issue by ariscn** [dropbox/pygerduty#34]
https://github.com/dropbox/pygerduty/issues/33 is a good start, but the `create_event()` function needs to be updated to use `request()`, or needs a similar modification.

**Comment by gmjosack** [comment]
Thanks for the report. If you'd like to send a pull request I'd be happy to merge it, otherwise I'll take a look early next week.

**Comment by ariscn** [comment]
Ping?

**Comment by gmjosack** [comment]
Sorry for the delay. Your fix has been pushed to pypi as 0.30.1
