### ISSUE TITLE
basic authentication does not work

### ISSUE THREAD

**Issue by hsmade** [dropbox/pygerduty#41]
from https://github.com/dropbox/pygerduty/blob/master/pygerduty/__init__.py#L663 : 
  "{0}:{1}".format(**self.basic_auth)

This doesn't work. It should be either:
 `` "{0}:{1}".format(*self.basic_auth)`` and use a tuple as argument on init
Or
``  "{username}:{password}".format(**self.basic_auth)`` and use a dict as argument on init.

**Comment by gmjosack** [comment]
I imagine that was broken when Python 3 support was added. While it's an easy fix I actually wonder if support for basic auth should just be removed instead. Considering it wouldn't have worked for a while now with no reports but also that it appears to be deprecated per the top comment on https://developer.pagerduty.com/documentation/rest/authentication

Do you have a specific need for basic auth support or did you come across this some other way?

**Comment by hsmade** [comment]
Just saw that message about it being deprecated as well. I'd say remove it, as it wouldn't work anyway.
