### ISSUE TITLE
Add support for the new V2 API

### ISSUE THREAD

**Issue by gmjosack** [dropbox/pygerduty#42]
https://v2.developer.pagerduty.com/

**Comment by gmjosack** [comment]
This task is complete with the following changesets: 839fb289ab4fdc4d515712b5995189939a91f064, 4362183744f79dd71915b4afd971b4cfba22f94f, c6a2639a070223d1d32cbf790074e07ebfe617f6, 92fb1b2cc1337d6ae95878d6fbba46bcbc5ce871, 92fb1b2cc1337d6ae95878d6fbba46bcbc5ce871, c4e2cd29f86671890d2166466f2e66c116ee0828 and released as 0.36.0 (https://pypi.python.org/pypi/pygerduty/0.36.0).

Thanks @khardsonhurley !

**Comment by khardsonhurley** [comment]
Now released as as 0.36.1 ([https://pypi.python.org/pypi/pygerduty/0.36.1](https://pypi.python.org/pypi/pygerduty/0.36.1)).

**Comment by jjinno** [comment]
Is there a reason that "requester_id" is being munged into the "From" parameter throughout v2 code?
Why not simply ask for the "From" parameter, since the "requester_id" is no longer used in the API?
