### ISSUE TITLE
getting event details from log_entries

### ISSUE THREAD

**Issue by i5uhail** [dropbox/pygerduty#47]
I am new to pygerduty and still exploring. 

I have a case were i need to get the event details from a log entry... 

I know get_trigger_log_entry() gets me the details but the return i am getting is just 
`<LogEntry: contexts=[], created_at=u'2016-05-02T11:42:42Z', agent=<Container: type=u'service'>, type=u'trigger', id=u'someID', channel=<Container: type=u'email', summary=u'SomeSummary'>>`

Is there a way i can completely get this info with pygerduty. The return of incidents.show has the link to 
the log entry but does not give me the content of it. 

Is there an attribute to get this content that I am missing. 

Can some one please help me with my requirement. Thanks in advance.

**Comment by gmjosack** [comment]
pygerduty is a pretty thin wrapper around the API and can do most things the API can do. If you want to get a list of `LogEntry`'s from an incident then you could call `log_entries.list()` on an incident. For example:

```
incident = pd.incidents.list().next()
for entry in incident.log_entries.list():
    print entry
```

Let me know if this is not what you're asking.

**Comment by i5uhail** [comment]
Thanks a lot for getting back @gmjosack 

I will be a bit more specific. I am looking for additional details of my alerts like body of the alerts which i can get from the pagerduty api 

https://(SomeDomain).pagerduty.com/api/v1/incidents/(:id)/log_entries/(LogEntry:id)?include[]=channel

is there a pygerduty way of fetching this details. Thanks in advance.

**Comment by gmjosack** [comment]
I believe that should work as one of the following:

```python
incident.log_entries.list(include=["channel"])
```

or

```python
incident.log_entries.show("SOME_ENTRY_ID", include=["channel"])
```

**Comment by i5uhail** [comment]
Thanks a lot @gmjosack that worked.
