### ISSUE TITLE
Issue Parsing Results Returned from PagerDuty

### ISSUE THREAD

**Issue by sjtarik** [dropbox/pygerduty#51]
With pygerduty 0.35.2 / python 2.7.10, when I request schedules, v1 api's return valid results but list or str calls to results end up with following error:

```
pager = pygerduty.PagerDuty(####,####)
schedules = pager.schedules.show(####)
```

```
 File "/Users/tarik/Desktop/devs/lib/python2.7/site-packages/pygerduty/__init__.py", line 176, in show
    return self.container(self, **response.get(self.sname, {}))
TypeError: __init__() got multiple values for keyword argument 'self'
```

Could it be PagerDuty changed api responses not in a backward-compatible way? Thx

**Comment by gmjosack** [comment]
Can you verify if you're using a v1 or v2 API token? When I test with a v1 token it works correctly, though if I use a v2 token I see a similar issue.

**Comment by sjtarik** [comment]
I used v2 api key. Closing the issue. Thanks for the quick response.
